"use client";

import './globals.css'
import type { Metadata } from 'next'
	
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

import { ReduxProviders } from './_components/redux/Providers'
import { SessionProvider } from "next-auth/react"
import { WagmiWrapper } from "./_components/web3/WagmiWrapper"

import Navbar from "./_components/Navbar"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="business">
      <body className={`${inter.variable}`}>
          <ReduxProviders>
            <SessionProvider>
              <WagmiWrapper>
                <Navbar />
                {children}
              </WagmiWrapper>
            </SessionProvider>
          </ReduxProviders>
      </body>
    </html>
  )
}
