"use client";

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { ReduxProviders } from './_components/redux/Providers'
import { SessionProvider } from "next-auth/react"
import { WagmiWrapper } from "./_components/web3/WagmiWrapper"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProviders>
          <SessionProvider>
            <WagmiWrapper>
              {children}
            </WagmiWrapper>
          </SessionProvider>
        </ReduxProviders>
      </body>
    </html>
  )
}
